spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db?characterEncoding=utf8
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE